# Generated by Django 5.0.6 on 2024-08-03 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='date_joined',
            new_name='created',
        ),
    ]
