# Generated by Django 5.0.7 on 2024-08-04 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0002_rename_date_joined_customuser_created'),
        ('booking_app', '0002_remove_booking_seat_booking_seat_number_delete_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trains', to='booking_app.train'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customuser', to='authentication_app.customuser'),
        ),
        migrations.AlterField(
            model_name='train',
            name='running_days',
            field=models.ManyToManyField(related_name='days', to='booking_app.day'),
        ),
    ]
