# Generated by Django 5.0.7 on 2024-08-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0005_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='source',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
